{{ $credentialSecret := .Values.cloudCredentialSecretName}}
{{- range $index, $machinepool := .Values.machinePools }}
apiVersion: rke-machine.cattle.io/v1
kind: DigitaloceanMachineTemplate
metadata:
  name: {{ $machinepool.name }}
spec:
  template:
    spec:
      common:
        cloudCredentialSecretName: {{ $credentialSecret }}
      accessToken: {{ $machinepool.accessToken }}
      backups: {{ $machinepool.backups }}
      image: {{ $machinepool.image }}
      ipv6: {{ $machinepool.ipv6 }}
      monitoring: {{ $machinepool.monitoring }}
      privateNetworking: {{ $machinepool.privateNetworking }}
      region: {{ $machinepool.region}}
      size: {{ $machinepool.size }}
      sshKeyContents: {{ $machinepool.sshKeyContents }}
      sshKeyFingerprint: {{ $machinepool.sshKeyFingerprint }}
      sshPort: {{ $machinepool.sshPort | quote }}
      sshUser: {{ $machinepool.sshUser }}
      tags: {{ $machinepool.tags }}
      userdata: {{ $machinepool.userdata }}
---
{{ end }}